# Generated by Django 4.0.3 on 2022-09-28 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='comment_on',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidders',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='coment_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bids',
        ),
        migrations.AddField(
            model_name='bid',
            name='bids',
            field=models.ManyToManyField(blank=True, to='auctions.listing'),
        ),
    ]
