# Generated by Django 4.0.3 on 2022-09-28 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_commenter_comment_comment_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bids',
        ),
        migrations.AddField(
            model_name='bid',
            name='bids',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.listing'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_on',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_on',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.listing'),
        ),
    ]
