# Generated by Django 4.0.3 on 2022-09-28 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bid_bids_bid_bids_remove_comment_comment_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='coment_by',
            new_name='comment_by',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(blank=True, to='auctions.listing')),
                ('wishlist_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
