# Generated by Django 4.0.3 on 2022-09-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_wishlist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
