# Generated by Django 4.0.3 on 2022-09-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_wishlist_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bids',
            new_name='bid_on',
        ),
    ]
