# Generated by Django 4.0.3 on 2022-09-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_bids_bid_bid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.listing'),
        ),
    ]
