# Generated by Django 4.0.3 on 2022-09-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_comment_comment_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='current_highest',
            field=models.BooleanField(default=False),
        ),
    ]
